"""baseline_initial_schema

Revision ID: 001
Revises: 
Create Date: 2026-05-31 09:04:11.060604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compliance_cases_thread_id', table_name='compliance_cases')
    op.drop_index('ix_leads_partner_name', table_name='leads')
    op.create_index(op.f('ix_leads_account_manager_id'), 'leads', ['account_manager_id'], unique=False)
    op.drop_index('ix_limit_orders_status', table_name='limit_orders')
    op.drop_index('ix_manual_achievements_target_id', table_name='manual_achievements')
    op.drop_index('ix_manual_achievements_user_id', table_name='manual_achievements')
    op.alter_column('tickets', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.alter_column('tickets', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_manual_achievements_user_id', 'manual_achievements', ['user_id'], unique=False)
    op.create_index('ix_manual_achievements_target_id', 'manual_achievements', ['target_id'], unique=False)
    op.create_index('ix_limit_orders_status', 'limit_orders', ['status'], unique=False)
    op.drop_index(op.f('ix_leads_account_manager_id'), table_name='leads')
    op.create_index('ix_leads_partner_name', 'leads', ['partner_name'], unique=False)
    op.create_index('ix_compliance_cases_thread_id', 'compliance_cases', ['gmail_thread_id'], unique=False)
    # ### end Alembic commands ###
